package edu.byui.www.spiritualthought;

import java.util.Random;

/**
 * Class returns random url tokens from lds.org.
 *
 * This class uses embedded array of lds.org url tokens and returns a random set.
 *
 * @author Julian Romero
 * @version 2016.1120
 * @since 1.0
 *
 */

public class GospelLibrary {

    /**
     * Method calls Get Library method.
     * @return String Array of url tokens for lds.org.
     */
    private String[] GospelLibrary()
    {
        return getLibrary();
    }

    /**
     * Method creates a url token two-dimensional array and returns one random set.
     *
     * @return String Array of lds.org url tokens.
     */
    public String[] getLibrary() {
        String[][] library = new String[][]
                {
                        {"ot", "gen", "Genesis", "1"},
                        {"ot", "gen", "Genesis", "2"},
                        {"ot", "gen", "Genesis", "3"},
                        {"ot", "gen", "Genesis", "4"},
                        {"ot", "gen", "Genesis", "5"},
                        {"ot", "gen", "Genesis", "6"},
                        {"ot", "gen", "Genesis", "7"},
                        {"ot", "gen", "Genesis", "8"},
                        {"ot", "gen", "Genesis", "9"},
                        {"ot", "gen", "Genesis", "10"},
                        {"ot", "gen", "Genesis", "11"},
                        {"ot", "gen", "Genesis", "12"},
                        {"ot", "gen", "Genesis", "13"},
                        {"ot", "gen", "Genesis", "14"},
                        {"ot", "gen", "Genesis", "15"},
                        {"ot", "gen", "Genesis", "16"},
                        {"ot", "gen", "Genesis", "17"},
                        {"ot", "gen", "Genesis", "18"},
                        {"ot", "gen", "Genesis", "19"},
                        {"ot", "gen", "Genesis", "20"},
                        {"ot", "gen", "Genesis", "21"},
                        {"ot", "gen", "Genesis", "22"},
                        {"ot", "gen", "Genesis", "23"},
                        {"ot", "gen", "Genesis", "24"},
                        {"ot", "gen", "Genesis", "25"},
                        {"ot", "gen", "Genesis", "26"},
                        {"ot", "gen", "Genesis", "27"},
                        {"ot", "gen", "Genesis", "28"},
                        {"ot", "gen", "Genesis", "29"},
                        {"ot", "gen", "Genesis", "30"},
                        {"ot", "gen", "Genesis", "31"},
                        {"ot", "gen", "Genesis", "32"},
                        {"ot", "gen", "Genesis", "33"},
                        {"ot", "gen", "Genesis", "34"},
                        {"ot", "gen", "Genesis", "35"},
                        {"ot", "gen", "Genesis", "36"},
                        {"ot", "gen", "Genesis", "37"},
                        {"ot", "gen", "Genesis", "38"},
                        {"ot", "gen", "Genesis", "39"},
                        {"ot", "gen", "Genesis", "40"},
                        {"ot", "gen", "Genesis", "41"},
                        {"ot", "gen", "Genesis", "42"},
                        {"ot", "gen", "Genesis", "43"},
                        {"ot", "gen", "Genesis", "44"},
                        {"ot", "gen", "Genesis", "45"},
                        {"ot", "gen", "Genesis", "46"},
                        {"ot", "gen", "Genesis", "47"},
                        {"ot", "gen", "Genesis", "48"},
                        {"ot", "gen", "Genesis", "49"},
                        {"ot", "gen", "Genesis", "50"},
                        {"ot", "ex", "Exodus", "1"},
                        {"ot", "ex", "Exodus", "2"},
                        {"ot", "ex", "Exodus", "3"},
                        {"ot", "ex", "Exodus", "4"},
                        {"ot", "ex", "Exodus", "5"},
                        {"ot", "ex", "Exodus", "6"},
                        {"ot", "ex", "Exodus", "7"},
                        {"ot", "ex", "Exodus", "8"},
                        {"ot", "ex", "Exodus", "9"},
                        {"ot", "ex", "Exodus", "10"},
                        {"ot", "ex", "Exodus", "11"},
                        {"ot", "ex", "Exodus", "12"},
                        {"ot", "ex", "Exodus", "13"},
                        {"ot", "ex", "Exodus", "14"},
                        {"ot", "ex", "Exodus", "15"},
                        {"ot", "ex", "Exodus", "16"},
                        {"ot", "ex", "Exodus", "17"},
                        {"ot", "ex", "Exodus", "18"},
                        {"ot", "ex", "Exodus", "19"},
                        {"ot", "ex", "Exodus", "20"},
                        {"ot", "ex", "Exodus", "21"},
                        {"ot", "ex", "Exodus", "22"},
                        {"ot", "ex", "Exodus", "23"},
                        {"ot", "ex", "Exodus", "24"},
                        {"ot", "ex", "Exodus", "25"},
                        {"ot", "ex", "Exodus", "26"},
                        {"ot", "ex", "Exodus", "27"},
                        {"ot", "ex", "Exodus", "28"},
                        {"ot", "ex", "Exodus", "29"},
                        {"ot", "ex", "Exodus", "30"},
                        {"ot", "ex", "Exodus", "31"},
                        {"ot", "ex", "Exodus", "32"},
                        {"ot", "ex", "Exodus", "33"},
                        {"ot", "ex", "Exodus", "34"},
                        {"ot", "ex", "Exodus", "35"},
                        {"ot", "ex", "Exodus", "36"},
                        {"ot", "ex", "Exodus", "37"},
                        {"ot", "ex", "Exodus", "38"},
                        {"ot", "ex", "Exodus", "39"},
                        {"ot", "ex", "Exodus", "40"},
                        {"ot", "lev", "Leviticus", "1"},
                        {"ot", "lev", "Leviticus", "2"},
                        {"ot", "lev", "Leviticus", "3"},
                        {"ot", "lev", "Leviticus", "4"},
                        {"ot", "lev", "Leviticus", "5"},
                        {"ot", "lev", "Leviticus", "6"},
                        {"ot", "lev", "Leviticus", "7"},
                        {"ot", "lev", "Leviticus", "8"},
                        {"ot", "lev", "Leviticus", "9"},
                        {"ot", "lev", "Leviticus", "10"},
                        {"ot", "lev", "Leviticus", "11"},
                        {"ot", "lev", "Leviticus", "12"},
                        {"ot", "lev", "Leviticus", "13"},
                        {"ot", "lev", "Leviticus", "14"},
                        {"ot", "lev", "Leviticus", "15"},
                        {"ot", "lev", "Leviticus", "16"},
                        {"ot", "lev", "Leviticus", "17"},
                        {"ot", "lev", "Leviticus", "18"},
                        {"ot", "lev", "Leviticus", "19"},
                        {"ot", "lev", "Leviticus", "20"},
                        {"ot", "lev", "Leviticus", "21"},
                        {"ot", "lev", "Leviticus", "22"},
                        {"ot", "lev", "Leviticus", "23"},
                        {"ot", "lev", "Leviticus", "24"},
                        {"ot", "lev", "Leviticus", "25"},
                        {"ot", "lev", "Leviticus", "26"},
                        {"ot", "lev", "Leviticus", "27"},
                        {"ot", "num", "Numbers", "1"},
                        {"ot", "num", "Numbers", "2"},
                        {"ot", "num", "Numbers", "3"},
                        {"ot", "num", "Numbers", "4"},
                        {"ot", "num", "Numbers", "5"},
                        {"ot", "num", "Numbers", "6"},
                        {"ot", "num", "Numbers", "7"},
                        {"ot", "num", "Numbers", "8"},
                        {"ot", "num", "Numbers", "9"},
                        {"ot", "num", "Numbers", "10"},
                        {"ot", "num", "Numbers", "11"},
                        {"ot", "num", "Numbers", "12"},
                        {"ot", "num", "Numbers", "13"},
                        {"ot", "num", "Numbers", "14"},
                        {"ot", "num", "Numbers", "15"},
                        {"ot", "num", "Numbers", "16"},
                        {"ot", "num", "Numbers", "17"},
                        {"ot", "num", "Numbers", "18"},
                        {"ot", "num", "Numbers", "19"},
                        {"ot", "num", "Numbers", "20"},
                        {"ot", "num", "Numbers", "21"},
                        {"ot", "num", "Numbers", "22"},
                        {"ot", "num", "Numbers", "23"},
                        {"ot", "num", "Numbers", "24"},
                        {"ot", "num", "Numbers", "25"},
                        {"ot", "num", "Numbers", "26"},
                        {"ot", "num", "Numbers", "27"},
                        {"ot", "num", "Numbers", "28"},
                        {"ot", "num", "Numbers", "29"},
                        {"ot", "num", "Numbers", "30"},
                        {"ot", "num", "Numbers", "31"},
                        {"ot", "num", "Numbers", "32"},
                        {"ot", "num", "Numbers", "33"},
                        {"ot", "num", "Numbers", "34"},
                        {"ot", "num", "Numbers", "35"},
                        {"ot", "num", "Numbers", "36"},
                        {"ot", "deut", "Deuteronomy", "1"},
                        {"ot", "deut", "Deuteronomy", "2"},
                        {"ot", "deut", "Deuteronomy", "3"},
                        {"ot", "deut", "Deuteronomy", "4"},
                        {"ot", "deut", "Deuteronomy", "5"},
                        {"ot", "deut", "Deuteronomy", "6"},
                        {"ot", "deut", "Deuteronomy", "7"},
                        {"ot", "deut", "Deuteronomy", "8"},
                        {"ot", "deut", "Deuteronomy", "9"},
                        {"ot", "deut", "Deuteronomy", "10"},
                        {"ot", "deut", "Deuteronomy", "11"},
                        {"ot", "deut", "Deuteronomy", "12"},
                        {"ot", "deut", "Deuteronomy", "13"},
                        {"ot", "deut", "Deuteronomy", "14"},
                        {"ot", "deut", "Deuteronomy", "15"},
                        {"ot", "deut", "Deuteronomy", "16"},
                        {"ot", "deut", "Deuteronomy", "17"},
                        {"ot", "deut", "Deuteronomy", "18"},
                        {"ot", "deut", "Deuteronomy", "19"},
                        {"ot", "deut", "Deuteronomy", "20"},
                        {"ot", "deut", "Deuteronomy", "21"},
                        {"ot", "deut", "Deuteronomy", "22"},
                        {"ot", "deut", "Deuteronomy", "23"},
                        {"ot", "deut", "Deuteronomy", "24"},
                        {"ot", "deut", "Deuteronomy", "25"},
                        {"ot", "deut", "Deuteronomy", "26"},
                        {"ot", "deut", "Deuteronomy", "27"},
                        {"ot", "deut", "Deuteronomy", "28"},
                        {"ot", "deut", "Deuteronomy", "29"},
                        {"ot", "deut", "Deuteronomy", "30"},
                        {"ot", "deut", "Deuteronomy", "31"},
                        {"ot", "deut", "Deuteronomy", "32"},
                        {"ot", "deut", "Deuteronomy", "33"},
                        {"ot", "deut", "Deuteronomy", "34"},
                        {"ot", "josh", "Joshua", "1"},
                        {"ot", "josh", "Joshua", "2"},
                        {"ot", "josh", "Joshua", "3"},
                        {"ot", "josh", "Joshua", "4"},
                        {"ot", "josh", "Joshua", "5"},
                        {"ot", "josh", "Joshua", "6"},
                        {"ot", "josh", "Joshua", "7"},
                        {"ot", "josh", "Joshua", "8"},
                        {"ot", "josh", "Joshua", "9"},
                        {"ot", "josh", "Joshua", "10"},
                        {"ot", "josh", "Joshua", "11"},
                        {"ot", "josh", "Joshua", "12"},
                        {"ot", "josh", "Joshua", "13"},
                        {"ot", "josh", "Joshua", "14"},
                        {"ot", "josh", "Joshua", "15"},
                        {"ot", "josh", "Joshua", "16"},
                        {"ot", "josh", "Joshua", "17"},
                        {"ot", "josh", "Joshua", "18"},
                        {"ot", "josh", "Joshua", "19"},
                        {"ot", "josh", "Joshua", "20"},
                        {"ot", "josh", "Joshua", "21"},
                        {"ot", "josh", "Joshua", "22"},
                        {"ot", "josh", "Joshua", "23"},
                        {"ot", "josh", "Joshua", "24"},
                        {"ot", "judg", "Judges", "1"},
                        {"ot", "judg", "Judges", "2"},
                        {"ot", "judg", "Judges", "3"},
                        {"ot", "judg", "Judges", "4"},
                        {"ot", "judg", "Judges", "5"},
                        {"ot", "judg", "Judges", "6"},
                        {"ot", "judg", "Judges", "7"},
                        {"ot", "judg", "Judges", "8"},
                        {"ot", "judg", "Judges", "9"},
                        {"ot", "judg", "Judges", "10"},
                        {"ot", "judg", "Judges", "11"},
                        {"ot", "judg", "Judges", "12"},
                        {"ot", "judg", "Judges", "13"},
                        {"ot", "judg", "Judges", "14"},
                        {"ot", "judg", "Judges", "15"},
                        {"ot", "judg", "Judges", "16"},
                        {"ot", "judg", "Judges", "17"},
                        {"ot", "judg", "Judges", "18"},
                        {"ot", "judg", "Judges", "19"},
                        {"ot", "judg", "Judges", "20"},
                        {"ot", "judg", "Judges", "21"},
                        {"ot", "ruth", "Ruth", "1"},
                        {"ot", "ruth", "Ruth", "2"},
                        {"ot", "ruth", "Ruth", "3"},
                        {"ot", "ruth", "Ruth", "4"},
                        {"ot", "1-sam", "1 Samuel", "1"},
                        {"ot", "1-sam", "1 Samuel", "2"},
                        {"ot", "1-sam", "1 Samuel", "3"},
                        {"ot", "1-sam", "1 Samuel", "4"},
                        {"ot", "1-sam", "1 Samuel", "5"},
                        {"ot", "1-sam", "1 Samuel", "6"},
                        {"ot", "1-sam", "1 Samuel", "7"},
                        {"ot", "1-sam", "1 Samuel", "8"},
                        {"ot", "1-sam", "1 Samuel", "9"},
                        {"ot", "1-sam", "1 Samuel", "10"},
                        {"ot", "1-sam", "1 Samuel", "11"},
                        {"ot", "1-sam", "1 Samuel", "12"},
                        {"ot", "1-sam", "1 Samuel", "13"},
                        {"ot", "1-sam", "1 Samuel", "14"},
                        {"ot", "1-sam", "1 Samuel", "15"},
                        {"ot", "1-sam", "1 Samuel", "16"},
                        {"ot", "1-sam", "1 Samuel", "17"},
                        {"ot", "1-sam", "1 Samuel", "18"},
                        {"ot", "1-sam", "1 Samuel", "19"},
                        {"ot", "1-sam", "1 Samuel", "20"},
                        {"ot", "1-sam", "1 Samuel", "21"},
                        {"ot", "1-sam", "1 Samuel", "22"},
                        {"ot", "1-sam", "1 Samuel", "23"},
                        {"ot", "1-sam", "1 Samuel", "24"},
                        {"ot", "1-sam", "1 Samuel", "25"},
                        {"ot", "1-sam", "1 Samuel", "26"},
                        {"ot", "1-sam", "1 Samuel", "27"},
                        {"ot", "1-sam", "1 Samuel", "28"},
                        {"ot", "1-sam", "1 Samuel", "29"},
                        {"ot", "1-sam", "1 Samuel", "30"},
                        {"ot", "1-sam", "1 Samuel", "31"},
                        {"ot", "2-sam", "2 Samuel", "1"},
                        {"ot", "2-sam", "2 Samuel", "2"},
                        {"ot", "2-sam", "2 Samuel", "3"},
                        {"ot", "2-sam", "2 Samuel", "4"},
                        {"ot", "2-sam", "2 Samuel", "5"},
                        {"ot", "2-sam", "2 Samuel", "6"},
                        {"ot", "2-sam", "2 Samuel", "7"},
                        {"ot", "2-sam", "2 Samuel", "8"},
                        {"ot", "2-sam", "2 Samuel", "9"},
                        {"ot", "2-sam", "2 Samuel", "10"},
                        {"ot", "2-sam", "2 Samuel", "11"},
                        {"ot", "2-sam", "2 Samuel", "12"},
                        {"ot", "2-sam", "2 Samuel", "13"},
                        {"ot", "2-sam", "2 Samuel", "14"},
                        {"ot", "2-sam", "2 Samuel", "15"},
                        {"ot", "2-sam", "2 Samuel", "16"},
                        {"ot", "2-sam", "2 Samuel", "17"},
                        {"ot", "2-sam", "2 Samuel", "18"},
                        {"ot", "2-sam", "2 Samuel", "19"},
                        {"ot", "2-sam", "2 Samuel", "20"},
                        {"ot", "2-sam", "2 Samuel", "21"},
                        {"ot", "2-sam", "2 Samuel", "22"},
                        {"ot", "2-sam", "2 Samuel", "23"},
                        {"ot", "2-sam", "2 Samuel", "24"},
                        {"ot", "1-kgs", "1 Kings", "1"},
                        {"ot", "1-kgs", "1 Kings", "2"},
                        {"ot", "1-kgs", "1 Kings", "3"},
                        {"ot", "1-kgs", "1 Kings", "4"},
                        {"ot", "1-kgs", "1 Kings", "5"},
                        {"ot", "1-kgs", "1 Kings", "6"},
                        {"ot", "1-kgs", "1 Kings", "7"},
                        {"ot", "1-kgs", "1 Kings", "8"},
                        {"ot", "1-kgs", "1 Kings", "9"},
                        {"ot", "1-kgs", "1 Kings", "10"},
                        {"ot", "1-kgs", "1 Kings", "11"},
                        {"ot", "1-kgs", "1 Kings", "12"},
                        {"ot", "1-kgs", "1 Kings", "13"},
                        {"ot", "1-kgs", "1 Kings", "14"},
                        {"ot", "1-kgs", "1 Kings", "15"},
                        {"ot", "1-kgs", "1 Kings", "16"},
                        {"ot", "1-kgs", "1 Kings", "17"},
                        {"ot", "1-kgs", "1 Kings", "18"},
                        {"ot", "1-kgs", "1 Kings", "19"},
                        {"ot", "1-kgs", "1 Kings", "20"},
                        {"ot", "1-kgs", "1 Kings", "21"},
                        {"ot", "1-kgs", "1 Kings", "22"},
                        {"ot", "2-kgs", "2 Kings", "1"},
                        {"ot", "2-kgs", "2 Kings", "2"},
                        {"ot", "2-kgs", "2 Kings", "3"},
                        {"ot", "2-kgs", "2 Kings", "4"},
                        {"ot", "2-kgs", "2 Kings", "5"},
                        {"ot", "2-kgs", "2 Kings", "6"},
                        {"ot", "2-kgs", "2 Kings", "7"},
                        {"ot", "2-kgs", "2 Kings", "8"},
                        {"ot", "2-kgs", "2 Kings", "9"},
                        {"ot", "2-kgs", "2 Kings", "10"},
                        {"ot", "2-kgs", "2 Kings", "11"},
                        {"ot", "2-kgs", "2 Kings", "12"},
                        {"ot", "2-kgs", "2 Kings", "13"},
                        {"ot", "2-kgs", "2 Kings", "14"},
                        {"ot", "2-kgs", "2 Kings", "15"},
                        {"ot", "2-kgs", "2 Kings", "16"},
                        {"ot", "2-kgs", "2 Kings", "17"},
                        {"ot", "2-kgs", "2 Kings", "18"},
                        {"ot", "2-kgs", "2 Kings", "19"},
                        {"ot", "2-kgs", "2 Kings", "20"},
                        {"ot", "2-kgs", "2 Kings", "21"},
                        {"ot", "2-kgs", "2 Kings", "22"},
                        {"ot", "2-kgs", "2 Kings", "23"},
                        {"ot", "2-kgs", "2 Kings", "24"},
                        {"ot", "2-kgs", "2 Kings", "25"},
                        {"ot", "1-chr", "1 Chronicles", "1"},
                        {"ot", "1-chr", "1 Chronicles", "2"},
                        {"ot", "1-chr", "1 Chronicles", "3"},
                        {"ot", "1-chr", "1 Chronicles", "4"},
                        {"ot", "1-chr", "1 Chronicles", "5"},
                        {"ot", "1-chr", "1 Chronicles", "6"},
                        {"ot", "1-chr", "1 Chronicles", "7"},
                        {"ot", "1-chr", "1 Chronicles", "8"},
                        {"ot", "1-chr", "1 Chronicles", "9"},
                        {"ot", "1-chr", "1 Chronicles", "10"},
                        {"ot", "1-chr", "1 Chronicles", "11"},
                        {"ot", "1-chr", "1 Chronicles", "12"},
                        {"ot", "1-chr", "1 Chronicles", "13"},
                        {"ot", "1-chr", "1 Chronicles", "14"},
                        {"ot", "1-chr", "1 Chronicles", "15"},
                        {"ot", "1-chr", "1 Chronicles", "16"},
                        {"ot", "1-chr", "1 Chronicles", "17"},
                        {"ot", "1-chr", "1 Chronicles", "18"},
                        {"ot", "1-chr", "1 Chronicles", "19"},
                        {"ot", "1-chr", "1 Chronicles", "20"},
                        {"ot", "1-chr", "1 Chronicles", "21"},
                        {"ot", "1-chr", "1 Chronicles", "22"},
                        {"ot", "1-chr", "1 Chronicles", "23"},
                        {"ot", "1-chr", "1 Chronicles", "24"},
                        {"ot", "1-chr", "1 Chronicles", "25"},
                        {"ot", "1-chr", "1 Chronicles", "26"},
                        {"ot", "1-chr", "1 Chronicles", "27"},
                        {"ot", "1-chr", "1 Chronicles", "28"},
                        {"ot", "1-chr", "1 Chronicles", "29"},
                        {"ot", "2-chr", "2 Chronicles", "1"},
                        {"ot", "2-chr", "2 Chronicles", "2"},
                        {"ot", "2-chr", "2 Chronicles", "3"},
                        {"ot", "2-chr", "2 Chronicles", "4"},
                        {"ot", "2-chr", "2 Chronicles", "5"},
                        {"ot", "2-chr", "2 Chronicles", "6"},
                        {"ot", "2-chr", "2 Chronicles", "7"},
                        {"ot", "2-chr", "2 Chronicles", "8"},
                        {"ot", "2-chr", "2 Chronicles", "9"},
                        {"ot", "2-chr", "2 Chronicles", "10"},
                        {"ot", "2-chr", "2 Chronicles", "11"},
                        {"ot", "2-chr", "2 Chronicles", "12"},
                        {"ot", "2-chr", "2 Chronicles", "13"},
                        {"ot", "2-chr", "2 Chronicles", "14"},
                        {"ot", "2-chr", "2 Chronicles", "15"},
                        {"ot", "2-chr", "2 Chronicles", "16"},
                        {"ot", "2-chr", "2 Chronicles", "17"},
                        {"ot", "2-chr", "2 Chronicles", "18"},
                        {"ot", "2-chr", "2 Chronicles", "19"},
                        {"ot", "2-chr", "2 Chronicles", "20"},
                        {"ot", "2-chr", "2 Chronicles", "21"},
                        {"ot", "2-chr", "2 Chronicles", "22"},
                        {"ot", "2-chr", "2 Chronicles", "23"},
                        {"ot", "2-chr", "2 Chronicles", "24"},
                        {"ot", "2-chr", "2 Chronicles", "25"},
                        {"ot", "2-chr", "2 Chronicles", "26"},
                        {"ot", "2-chr", "2 Chronicles", "27"},
                        {"ot", "2-chr", "2 Chronicles", "28"},
                        {"ot", "2-chr", "2 Chronicles", "29"},
                        {"ot", "2-chr", "2 Chronicles", "30"},
                        {"ot", "2-chr", "2 Chronicles", "31"},
                        {"ot", "2-chr", "2 Chronicles", "32"},
                        {"ot", "2-chr", "2 Chronicles", "33"},
                        {"ot", "2-chr", "2 Chronicles", "34"},
                        {"ot", "2-chr", "2 Chronicles", "35"},
                        {"ot", "2-chr", "2 Chronicles", "36"},
                        {"ot", "ezra", "Ezra", "1"},
                        {"ot", "ezra", "Ezra", "2"},
                        {"ot", "ezra", "Ezra", "3"},
                        {"ot", "ezra", "Ezra", "4"},
                        {"ot", "ezra", "Ezra", "5"},
                        {"ot", "ezra", "Ezra", "6"},
                        {"ot", "ezra", "Ezra", "7"},
                        {"ot", "ezra", "Ezra", "8"},
                        {"ot", "ezra", "Ezra", "9"},
                        {"ot", "ezra", "Ezra", "10"},
                        {"ot", "neh", "Nehemiah", "1"},
                        {"ot", "neh", "Nehemiah", "2"},
                        {"ot", "neh", "Nehemiah", "3"},
                        {"ot", "neh", "Nehemiah", "4"},
                        {"ot", "neh", "Nehemiah", "5"},
                        {"ot", "neh", "Nehemiah", "6"},
                        {"ot", "neh", "Nehemiah", "7"},
                        {"ot", "neh", "Nehemiah", "8"},
                        {"ot", "neh", "Nehemiah", "9"},
                        {"ot", "neh", "Nehemiah", "10"},
                        {"ot", "neh", "Nehemiah", "11"},
                        {"ot", "neh", "Nehemiah", "12"},
                        {"ot", "neh", "Nehemiah", "13"},
                        {"ot", "esth", "Esther", "1"},
                        {"ot", "esth", "Esther", "2"},
                        {"ot", "esth", "Esther", "3"},
                        {"ot", "esth", "Esther", "4"},
                        {"ot", "esth", "Esther", "5"},
                        {"ot", "esth", "Esther", "6"},
                        {"ot", "esth", "Esther", "7"},
                        {"ot", "esth", "Esther", "8"},
                        {"ot", "esth", "Esther", "9"},
                        {"ot", "esth", "Esther", "10"},
                        {"ot", "job", "Job", "1"},
                        {"ot", "job", "Job", "2"},
                        {"ot", "job", "Job", "3"},
                        {"ot", "job", "Job", "4"},
                        {"ot", "job", "Job", "5"},
                        {"ot", "job", "Job", "6"},
                        {"ot", "job", "Job", "7"},
                        {"ot", "job", "Job", "8"},
                        {"ot", "job", "Job", "9"},
                        {"ot", "job", "Job", "10"},
                        {"ot", "job", "Job", "11"},
                        {"ot", "job", "Job", "12"},
                        {"ot", "job", "Job", "13"},
                        {"ot", "job", "Job", "14"},
                        {"ot", "job", "Job", "15"},
                        {"ot", "job", "Job", "16"},
                        {"ot", "job", "Job", "17"},
                        {"ot", "job", "Job", "18"},
                        {"ot", "job", "Job", "19"},
                        {"ot", "job", "Job", "20"},
                        {"ot", "job", "Job", "21"},
                        {"ot", "job", "Job", "22"},
                        {"ot", "job", "Job", "23"},
                        {"ot", "job", "Job", "24"},
                        {"ot", "job", "Job", "25"},
                        {"ot", "job", "Job", "26"},
                        {"ot", "job", "Job", "27"},
                        {"ot", "job", "Job", "28"},
                        {"ot", "job", "Job", "29"},
                        {"ot", "job", "Job", "30"},
                        {"ot", "job", "Job", "31"},
                        {"ot", "job", "Job", "32"},
                        {"ot", "job", "Job", "33"},
                        {"ot", "job", "Job", "34"},
                        {"ot", "job", "Job", "35"},
                        {"ot", "job", "Job", "36"},
                        {"ot", "job", "Job", "37"},
                        {"ot", "job", "Job", "38"},
                        {"ot", "job", "Job", "39"},
                        {"ot", "job", "Job", "40"},
                        {"ot", "job", "Job", "41"},
                        {"ot", "job", "Job", "42"},
                        {"ot", "ps", "Psalms", "1"},
                        {"ot", "ps", "Psalms", "2"},
                        {"ot", "ps", "Psalms", "3"},
                        {"ot", "ps", "Psalms", "4"},
                        {"ot", "ps", "Psalms", "5"},
                        {"ot", "ps", "Psalms", "6"},
                        {"ot", "ps", "Psalms", "7"},
                        {"ot", "ps", "Psalms", "8"},
                        {"ot", "ps", "Psalms", "9"},
                        {"ot", "ps", "Psalms", "10"},
                        {"ot", "ps", "Psalms", "11"},
                        {"ot", "ps", "Psalms", "12"},
                        {"ot", "ps", "Psalms", "13"},
                        {"ot", "ps", "Psalms", "14"},
                        {"ot", "ps", "Psalms", "15"},
                        {"ot", "ps", "Psalms", "16"},
                        {"ot", "ps", "Psalms", "17"},
                        {"ot", "ps", "Psalms", "18"},
                        {"ot", "ps", "Psalms", "19"},
                        {"ot", "ps", "Psalms", "20"},
                        {"ot", "ps", "Psalms", "21"},
                        {"ot", "ps", "Psalms", "22"},
                        {"ot", "ps", "Psalms", "23"},
                        {"ot", "ps", "Psalms", "24"},
                        {"ot", "ps", "Psalms", "25"},
                        {"ot", "ps", "Psalms", "26"},
                        {"ot", "ps", "Psalms", "27"},
                        {"ot", "ps", "Psalms", "28"},
                        {"ot", "ps", "Psalms", "29"},
                        {"ot", "ps", "Psalms", "30"},
                        {"ot", "ps", "Psalms", "31"},
                        {"ot", "ps", "Psalms", "32"},
                        {"ot", "ps", "Psalms", "33"},
                        {"ot", "ps", "Psalms", "34"},
                        {"ot", "ps", "Psalms", "35"},
                        {"ot", "ps", "Psalms", "36"},
                        {"ot", "ps", "Psalms", "37"},
                        {"ot", "ps", "Psalms", "38"},
                        {"ot", "ps", "Psalms", "39"},
                        {"ot", "ps", "Psalms", "40"},
                        {"ot", "ps", "Psalms", "41"},
                        {"ot", "ps", "Psalms", "42"},
                        {"ot", "ps", "Psalms", "43"},
                        {"ot", "ps", "Psalms", "44"},
                        {"ot", "ps", "Psalms", "45"},
                        {"ot", "ps", "Psalms", "46"},
                        {"ot", "ps", "Psalms", "47"},
                        {"ot", "ps", "Psalms", "48"},
                        {"ot", "ps", "Psalms", "49"},
                        {"ot", "ps", "Psalms", "50"},
                        {"ot", "ps", "Psalms", "51"},
                        {"ot", "ps", "Psalms", "52"},
                        {"ot", "ps", "Psalms", "53"},
                        {"ot", "ps", "Psalms", "54"},
                        {"ot", "ps", "Psalms", "55"},
                        {"ot", "ps", "Psalms", "56"},
                        {"ot", "ps", "Psalms", "57"},
                        {"ot", "ps", "Psalms", "58"},
                        {"ot", "ps", "Psalms", "59"},
                        {"ot", "ps", "Psalms", "60"},
                        {"ot", "ps", "Psalms", "61"},
                        {"ot", "ps", "Psalms", "62"},
                        {"ot", "ps", "Psalms", "63"},
                        {"ot", "ps", "Psalms", "64"},
                        {"ot", "ps", "Psalms", "65"},
                        {"ot", "ps", "Psalms", "66"},
                        {"ot", "ps", "Psalms", "67"},
                        {"ot", "ps", "Psalms", "68"},
                        {"ot", "ps", "Psalms", "69"},
                        {"ot", "ps", "Psalms", "70"},
                        {"ot", "ps", "Psalms", "71"},
                        {"ot", "ps", "Psalms", "72"},
                        {"ot", "ps", "Psalms", "73"},
                        {"ot", "ps", "Psalms", "74"},
                        {"ot", "ps", "Psalms", "75"},
                        {"ot", "ps", "Psalms", "76"},
                        {"ot", "ps", "Psalms", "77"},
                        {"ot", "ps", "Psalms", "78"},
                        {"ot", "ps", "Psalms", "79"},
                        {"ot", "ps", "Psalms", "80"},
                        {"ot", "ps", "Psalms", "81"},
                        {"ot", "ps", "Psalms", "82"},
                        {"ot", "ps", "Psalms", "83"},
                        {"ot", "ps", "Psalms", "84"},
                        {"ot", "ps", "Psalms", "85"},
                        {"ot", "ps", "Psalms", "86"},
                        {"ot", "ps", "Psalms", "87"},
                        {"ot", "ps", "Psalms", "88"},
                        {"ot", "ps", "Psalms", "89"},
                        {"ot", "ps", "Psalms", "90"},
                        {"ot", "ps", "Psalms", "91"},
                        {"ot", "ps", "Psalms", "92"},
                        {"ot", "ps", "Psalms", "93"},
                        {"ot", "ps", "Psalms", "94"},
                        {"ot", "ps", "Psalms", "95"},
                        {"ot", "ps", "Psalms", "96"},
                        {"ot", "ps", "Psalms", "97"},
                        {"ot", "ps", "Psalms", "98"},
                        {"ot", "ps", "Psalms", "99"},
                        {"ot", "ps", "Psalms", "100"},
                        {"ot", "ps", "Psalms", "101"},
                        {"ot", "ps", "Psalms", "102"},
                        {"ot", "ps", "Psalms", "103"},
                        {"ot", "ps", "Psalms", "104"},
                        {"ot", "ps", "Psalms", "105"},
                        {"ot", "ps", "Psalms", "106"},
                        {"ot", "ps", "Psalms", "107"},
                        {"ot", "ps", "Psalms", "108"},
                        {"ot", "ps", "Psalms", "109"},
                        {"ot", "ps", "Psalms", "110"},
                        {"ot", "ps", "Psalms", "111"},
                        {"ot", "ps", "Psalms", "112"},
                        {"ot", "ps", "Psalms", "113"},
                        {"ot", "ps", "Psalms", "114"},
                        {"ot", "ps", "Psalms", "115"},
                        {"ot", "ps", "Psalms", "116"},
                        {"ot", "ps", "Psalms", "117"},
                        {"ot", "ps", "Psalms", "118"},
                        {"ot", "ps", "Psalms", "119"},
                        {"ot", "ps", "Psalms", "120"},
                        {"ot", "ps", "Psalms", "121"},
                        {"ot", "ps", "Psalms", "122"},
                        {"ot", "ps", "Psalms", "123"},
                        {"ot", "ps", "Psalms", "124"},
                        {"ot", "ps", "Psalms", "125"},
                        {"ot", "ps", "Psalms", "126"},
                        {"ot", "ps", "Psalms", "127"},
                        {"ot", "ps", "Psalms", "128"},
                        {"ot", "ps", "Psalms", "129"},
                        {"ot", "ps", "Psalms", "130"},
                        {"ot", "ps", "Psalms", "131"},
                        {"ot", "ps", "Psalms", "132"},
                        {"ot", "ps", "Psalms", "133"},
                        {"ot", "ps", "Psalms", "134"},
                        {"ot", "ps", "Psalms", "135"},
                        {"ot", "ps", "Psalms", "136"},
                        {"ot", "ps", "Psalms", "137"},
                        {"ot", "ps", "Psalms", "138"},
                        {"ot", "ps", "Psalms", "139"},
                        {"ot", "ps", "Psalms", "140"},
                        {"ot", "ps", "Psalms", "141"},
                        {"ot", "ps", "Psalms", "142"},
                        {"ot", "ps", "Psalms", "143"},
                        {"ot", "ps", "Psalms", "144"},
                        {"ot", "ps", "Psalms", "145"},
                        {"ot", "ps", "Psalms", "146"},
                        {"ot", "ps", "Psalms", "147"},
                        {"ot", "ps", "Psalms", "148"},
                        {"ot", "ps", "Psalms", "149"},
                        {"ot", "ps", "Psalms", "150"},
                        {"ot", "prov", "Proverbs", "1"},
                        {"ot", "prov", "Proverbs", "2"},
                        {"ot", "prov", "Proverbs", "3"},
                        {"ot", "prov", "Proverbs", "4"},
                        {"ot", "prov", "Proverbs", "5"},
                        {"ot", "prov", "Proverbs", "6"},
                        {"ot", "prov", "Proverbs", "7"},
                        {"ot", "prov", "Proverbs", "8"},
                        {"ot", "prov", "Proverbs", "9"},
                        {"ot", "prov", "Proverbs", "10"},
                        {"ot", "prov", "Proverbs", "11"},
                        {"ot", "prov", "Proverbs", "12"},
                        {"ot", "prov", "Proverbs", "13"},
                        {"ot", "prov", "Proverbs", "14"},
                        {"ot", "prov", "Proverbs", "15"},
                        {"ot", "prov", "Proverbs", "16"},
                        {"ot", "prov", "Proverbs", "17"},
                        {"ot", "prov", "Proverbs", "18"},
                        {"ot", "prov", "Proverbs", "19"},
                        {"ot", "prov", "Proverbs", "20"},
                        {"ot", "prov", "Proverbs", "21"},
                        {"ot", "prov", "Proverbs", "22"},
                        {"ot", "prov", "Proverbs", "23"},
                        {"ot", "prov", "Proverbs", "24"},
                        {"ot", "prov", "Proverbs", "25"},
                        {"ot", "prov", "Proverbs", "26"},
                        {"ot", "prov", "Proverbs", "27"},
                        {"ot", "prov", "Proverbs", "28"},
                        {"ot", "prov", "Proverbs", "29"},
                        {"ot", "prov", "Proverbs", "30"},
                        {"ot", "prov", "Proverbs", "31"},
                        {"ot", "eccl", "Ecclesiastes", "1"},
                        {"ot", "eccl", "Ecclesiastes", "2"},
                        {"ot", "eccl", "Ecclesiastes", "3"},
                        {"ot", "eccl", "Ecclesiastes", "4"},
                        {"ot", "eccl", "Ecclesiastes", "5"},
                        {"ot", "eccl", "Ecclesiastes", "6"},
                        {"ot", "eccl", "Ecclesiastes", "7"},
                        {"ot", "eccl", "Ecclesiastes", "8"},
                        {"ot", "eccl", "Ecclesiastes", "9"},
                        {"ot", "eccl", "Ecclesiastes", "10"},
                        {"ot", "eccl", "Ecclesiastes", "11"},
                        {"ot", "eccl", "Ecclesiastes", "12"},
                        {"ot", "song", "Solomon's Song", "1"},
                        {"ot", "song", "Solomon's Song", "2"},
                        {"ot", "song", "Solomon's Song", "3"},
                        {"ot", "song", "Solomon's Song", "4"},
                        {"ot", "song", "Solomon's Song", "5"},
                        {"ot", "song", "Solomon's Song", "6"},
                        {"ot", "song", "Solomon's Song", "7"},
                        {"ot", "song", "Solomon's Song", "8"},
                        {"ot", "isa", "Isaiah", "1"},
                        {"ot", "isa", "Isaiah", "2"},
                        {"ot", "isa", "Isaiah", "3"},
                        {"ot", "isa", "Isaiah", "4"},
                        {"ot", "isa", "Isaiah", "5"},
                        {"ot", "isa", "Isaiah", "6"},
                        {"ot", "isa", "Isaiah", "7"},
                        {"ot", "isa", "Isaiah", "8"},
                        {"ot", "isa", "Isaiah", "9"},
                        {"ot", "isa", "Isaiah", "10"},
                        {"ot", "isa", "Isaiah", "11"},
                        {"ot", "isa", "Isaiah", "12"},
                        {"ot", "isa", "Isaiah", "13"},
                        {"ot", "isa", "Isaiah", "14"},
                        {"ot", "isa", "Isaiah", "15"},
                        {"ot", "isa", "Isaiah", "16"},
                        {"ot", "isa", "Isaiah", "17"},
                        {"ot", "isa", "Isaiah", "18"},
                        {"ot", "isa", "Isaiah", "19"},
                        {"ot", "isa", "Isaiah", "20"},
                        {"ot", "isa", "Isaiah", "21"},
                        {"ot", "isa", "Isaiah", "22"},
                        {"ot", "isa", "Isaiah", "23"},
                        {"ot", "isa", "Isaiah", "24"},
                        {"ot", "isa", "Isaiah", "25"},
                        {"ot", "isa", "Isaiah", "26"},
                        {"ot", "isa", "Isaiah", "27"},
                        {"ot", "isa", "Isaiah", "28"},
                        {"ot", "isa", "Isaiah", "29"},
                        {"ot", "isa", "Isaiah", "30"},
                        {"ot", "isa", "Isaiah", "31"},
                        {"ot", "isa", "Isaiah", "32"},
                        {"ot", "isa", "Isaiah", "33"},
                        {"ot", "isa", "Isaiah", "34"},
                        {"ot", "isa", "Isaiah", "35"},
                        {"ot", "isa", "Isaiah", "36"},
                        {"ot", "isa", "Isaiah", "37"},
                        {"ot", "isa", "Isaiah", "38"},
                        {"ot", "isa", "Isaiah", "39"},
                        {"ot", "isa", "Isaiah", "40"},
                        {"ot", "isa", "Isaiah", "41"},
                        {"ot", "isa", "Isaiah", "42"},
                        {"ot", "isa", "Isaiah", "43"},
                        {"ot", "isa", "Isaiah", "44"},
                        {"ot", "isa", "Isaiah", "45"},
                        {"ot", "isa", "Isaiah", "46"},
                        {"ot", "isa", "Isaiah", "47"},
                        {"ot", "isa", "Isaiah", "48"},
                        {"ot", "isa", "Isaiah", "49"},
                        {"ot", "isa", "Isaiah", "50"},
                        {"ot", "isa", "Isaiah", "51"},
                        {"ot", "isa", "Isaiah", "52"},
                        {"ot", "isa", "Isaiah", "53"},
                        {"ot", "isa", "Isaiah", "54"},
                        {"ot", "isa", "Isaiah", "55"},
                        {"ot", "isa", "Isaiah", "56"},
                        {"ot", "isa", "Isaiah", "57"},
                        {"ot", "isa", "Isaiah", "58"},
                        {"ot", "isa", "Isaiah", "59"},
                        {"ot", "isa", "Isaiah", "60"},
                        {"ot", "isa", "Isaiah", "61"},
                        {"ot", "isa", "Isaiah", "62"},
                        {"ot", "isa", "Isaiah", "63"},
                        {"ot", "isa", "Isaiah", "64"},
                        {"ot", "isa", "Isaiah", "65"},
                        {"ot", "isa", "Isaiah", "66"},
                        {"ot", "jer", "Jeremiah", "1"},
                        {"ot", "jer", "Jeremiah", "2"},
                        {"ot", "jer", "Jeremiah", "3"},
                        {"ot", "jer", "Jeremiah", "4"},
                        {"ot", "jer", "Jeremiah", "5"},
                        {"ot", "jer", "Jeremiah", "6"},
                        {"ot", "jer", "Jeremiah", "7"},
                        {"ot", "jer", "Jeremiah", "8"},
                        {"ot", "jer", "Jeremiah", "9"},
                        {"ot", "jer", "Jeremiah", "10"},
                        {"ot", "jer", "Jeremiah", "11"},
                        {"ot", "jer", "Jeremiah", "12"},
                        {"ot", "jer", "Jeremiah", "13"},
                        {"ot", "jer", "Jeremiah", "14"},
                        {"ot", "jer", "Jeremiah", "15"},
                        {"ot", "jer", "Jeremiah", "16"},
                        {"ot", "jer", "Jeremiah", "17"},
                        {"ot", "jer", "Jeremiah", "18"},
                        {"ot", "jer", "Jeremiah", "19"},
                        {"ot", "jer", "Jeremiah", "20"},
                        {"ot", "jer", "Jeremiah", "21"},
                        {"ot", "jer", "Jeremiah", "22"},
                        {"ot", "jer", "Jeremiah", "23"},
                        {"ot", "jer", "Jeremiah", "24"},
                        {"ot", "jer", "Jeremiah", "25"},
                        {"ot", "jer", "Jeremiah", "26"},
                        {"ot", "jer", "Jeremiah", "27"},
                        {"ot", "jer", "Jeremiah", "28"},
                        {"ot", "jer", "Jeremiah", "29"},
                        {"ot", "jer", "Jeremiah", "30"},
                        {"ot", "jer", "Jeremiah", "31"},
                        {"ot", "jer", "Jeremiah", "32"},
                        {"ot", "jer", "Jeremiah", "33"},
                        {"ot", "jer", "Jeremiah", "34"},
                        {"ot", "jer", "Jeremiah", "35"},
                        {"ot", "jer", "Jeremiah", "36"},
                        {"ot", "jer", "Jeremiah", "37"},
                        {"ot", "jer", "Jeremiah", "38"},
                        {"ot", "jer", "Jeremiah", "39"},
                        {"ot", "jer", "Jeremiah", "40"},
                        {"ot", "jer", "Jeremiah", "41"},
                        {"ot", "jer", "Jeremiah", "42"},
                        {"ot", "jer", "Jeremiah", "43"},
                        {"ot", "jer", "Jeremiah", "44"},
                        {"ot", "jer", "Jeremiah", "45"},
                        {"ot", "jer", "Jeremiah", "46"},
                        {"ot", "jer", "Jeremiah", "47"},
                        {"ot", "jer", "Jeremiah", "48"},
                        {"ot", "jer", "Jeremiah", "49"},
                        {"ot", "jer", "Jeremiah", "50"},
                        {"ot", "jer", "Jeremiah", "51"},
                        {"ot", "jer", "Jeremiah", "52"},
                        {"ot", "lam", "Lamentations", "1"},
                        {"ot", "lam", "Lamentations", "2"},
                        {"ot", "lam", "Lamentations", "3"},
                        {"ot", "lam", "Lamentations", "4"},
                        {"ot", "lam", "Lamentations", "5"},
                        {"ot", "ezek", "Ezekiel", "1"},
                        {"ot", "ezek", "Ezekiel", "2"},
                        {"ot", "ezek", "Ezekiel", "3"},
                        {"ot", "ezek", "Ezekiel", "4"},
                        {"ot", "ezek", "Ezekiel", "5"},
                        {"ot", "ezek", "Ezekiel", "6"},
                        {"ot", "ezek", "Ezekiel", "7"},
                        {"ot", "ezek", "Ezekiel", "8"},
                        {"ot", "ezek", "Ezekiel", "9"},
                        {"ot", "ezek", "Ezekiel", "10"},
                        {"ot", "ezek", "Ezekiel", "11"},
                        {"ot", "ezek", "Ezekiel", "12"},
                        {"ot", "ezek", "Ezekiel", "13"},
                        {"ot", "ezek", "Ezekiel", "14"},
                        {"ot", "ezek", "Ezekiel", "15"},
                        {"ot", "ezek", "Ezekiel", "16"},
                        {"ot", "ezek", "Ezekiel", "17"},
                        {"ot", "ezek", "Ezekiel", "18"},
                        {"ot", "ezek", "Ezekiel", "19"},
                        {"ot", "ezek", "Ezekiel", "20"},
                        {"ot", "ezek", "Ezekiel", "21"},
                        {"ot", "ezek", "Ezekiel", "22"},
                        {"ot", "ezek", "Ezekiel", "23"},
                        {"ot", "ezek", "Ezekiel", "24"},
                        {"ot", "ezek", "Ezekiel", "25"},
                        {"ot", "ezek", "Ezekiel", "26"},
                        {"ot", "ezek", "Ezekiel", "27"},
                        {"ot", "ezek", "Ezekiel", "28"},
                        {"ot", "ezek", "Ezekiel", "29"},
                        {"ot", "ezek", "Ezekiel", "30"},
                        {"ot", "ezek", "Ezekiel", "31"},
                        {"ot", "ezek", "Ezekiel", "32"},
                        {"ot", "ezek", "Ezekiel", "33"},
                        {"ot", "ezek", "Ezekiel", "34"},
                        {"ot", "ezek", "Ezekiel", "35"},
                        {"ot", "ezek", "Ezekiel", "36"},
                        {"ot", "ezek", "Ezekiel", "37"},
                        {"ot", "ezek", "Ezekiel", "38"},
                        {"ot", "ezek", "Ezekiel", "39"},
                        {"ot", "ezek", "Ezekiel", "40"},
                        {"ot", "ezek", "Ezekiel", "41"},
                        {"ot", "ezek", "Ezekiel", "42"},
                        {"ot", "ezek", "Ezekiel", "43"},
                        {"ot", "ezek", "Ezekiel", "44"},
                        {"ot", "ezek", "Ezekiel", "45"},
                        {"ot", "ezek", "Ezekiel", "46"},
                        {"ot", "ezek", "Ezekiel", "47"},
                        {"ot", "ezek", "Ezekiel", "48"},
                        {"ot", "dan", "Daniel", "1"},
                        {"ot", "dan", "Daniel", "2"},
                        {"ot", "dan", "Daniel", "3"},
                        {"ot", "dan", "Daniel", "4"},
                        {"ot", "dan", "Daniel", "5"},
                        {"ot", "dan", "Daniel", "6"},
                        {"ot", "dan", "Daniel", "7"},
                        {"ot", "dan", "Daniel", "8"},
                        {"ot", "dan", "Daniel", "9"},
                        {"ot", "dan", "Daniel", "10"},
                        {"ot", "dan", "Daniel", "11"},
                        {"ot", "dan", "Daniel", "12"},
                        {"ot", "hosea", "Hosea", "1"},
                        {"ot", "hosea", "Hosea", "2"},
                        {"ot", "hosea", "Hosea", "3"},
                        {"ot", "hosea", "Hosea", "4"},
                        {"ot", "hosea", "Hosea", "5"},
                        {"ot", "hosea", "Hosea", "6"},
                        {"ot", "hosea", "Hosea", "7"},
                        {"ot", "hosea", "Hosea", "8"},
                        {"ot", "hosea", "Hosea", "9"},
                        {"ot", "hosea", "Hosea", "10"},
                        {"ot", "hosea", "Hosea", "11"},
                        {"ot", "hosea", "Hosea", "12"},
                        {"ot", "hosea", "Hosea", "13"},
                        {"ot", "hosea", "Hosea", "14"},
                        {"ot", "joel", "Joel", "1"},
                        {"ot", "joel", "Joel", "2"},
                        {"ot", "joel", "Joel", "3"},
                        {"ot", "amos", "Amos", "1"},
                        {"ot", "amos", "Amos", "2"},
                        {"ot", "amos", "Amos", "3"},
                        {"ot", "amos", "Amos", "4"},
                        {"ot", "amos", "Amos", "5"},
                        {"ot", "amos", "Amos", "6"},
                        {"ot", "amos", "Amos", "7"},
                        {"ot", "amos", "Amos", "8"},
                        {"ot", "amos", "Amos", "9"},
                        {"ot", "obad", "Obadiah", "1"},
                        {"ot", "jonah", "Jonah", "1"},
                        {"ot", "jonah", "Jonah", "2"},
                        {"ot", "jonah", "Jonah", "3"},
                        {"ot", "jonah", "Jonah", "4"},
                        {"ot", "micah", "Micah", "1"},
                        {"ot", "micah", "Micah", "2"},
                        {"ot", "micah", "Micah", "3"},
                        {"ot", "micah", "Micah", "4"},
                        {"ot", "micah", "Micah", "5"},
                        {"ot", "micah", "Micah", "6"},
                        {"ot", "micah", "Micah", "7"},
                        {"ot", "nahum", "Nahum", "1"},
                        {"ot", "nahum", "Nahum", "2"},
                        {"ot", "nahum", "Nahum", "3"},
                        {"ot", "hab", "Habakkuk", "1"},
                        {"ot", "hab", "Habakkuk", "2"},
                        {"ot", "hab", "Habakkuk", "3"},
                        {"ot", "zeph", "Zephaniah", "1"},
                        {"ot", "zeph", "Zephaniah", "2"},
                        {"ot", "zeph", "Zephaniah", "3"},
                        {"ot", "hag", "Haggai", "1"},
                        {"ot", "hag", "Haggai", "2"},
                        {"ot", "zech", "Zechariah", "1"},
                        {"ot", "zech", "Zechariah", "2"},
                        {"ot", "zech", "Zechariah", "3"},
                        {"ot", "zech", "Zechariah", "4"},
                        {"ot", "zech", "Zechariah", "5"},
                        {"ot", "zech", "Zechariah", "6"},
                        {"ot", "zech", "Zechariah", "7"},
                        {"ot", "zech", "Zechariah", "8"},
                        {"ot", "zech", "Zechariah", "9"},
                        {"ot", "zech", "Zechariah", "10"},
                        {"ot", "zech", "Zechariah", "11"},
                        {"ot", "zech", "Zechariah", "12"},
                        {"ot", "zech", "Zechariah", "13"},
                        {"ot", "zech", "Zechariah", "14"},
                        {"ot", "mal", "Malachi", "1"},
                        {"ot", "mal", "Malachi", "2"},
                        {"ot", "mal", "Malachi", "3"},
                        {"ot", "mal", "Malachi", "4"},
                        {"nt", "matt", "Matthew", "1"},
                        {"nt", "matt", "Matthew", "2"},
                        {"nt", "matt", "Matthew", "3"},
                        {"nt", "matt", "Matthew", "4"},
                        {"nt", "matt", "Matthew", "5"},
                        {"nt", "matt", "Matthew", "6"},
                        {"nt", "matt", "Matthew", "7"},
                        {"nt", "matt", "Matthew", "8"},
                        {"nt", "matt", "Matthew", "9"},
                        {"nt", "matt", "Matthew", "10"},
                        {"nt", "matt", "Matthew", "11"},
                        {"nt", "matt", "Matthew", "12"},
                        {"nt", "matt", "Matthew", "13"},
                        {"nt", "matt", "Matthew", "14"},
                        {"nt", "matt", "Matthew", "15"},
                        {"nt", "matt", "Matthew", "16"},
                        {"nt", "matt", "Matthew", "17"},
                        {"nt", "matt", "Matthew", "18"},
                        {"nt", "matt", "Matthew", "19"},
                        {"nt", "matt", "Matthew", "20"},
                        {"nt", "matt", "Matthew", "21"},
                        {"nt", "matt", "Matthew", "22"},
                        {"nt", "matt", "Matthew", "23"},
                        {"nt", "matt", "Matthew", "24"},
                        {"nt", "matt", "Matthew", "25"},
                        {"nt", "matt", "Matthew", "26"},
                        {"nt", "matt", "Matthew", "27"},
                        {"nt", "matt", "Matthew", "28"},
                        {"nt", "mark", "Mark", "1"},
                        {"nt", "mark", "Mark", "2"},
                        {"nt", "mark", "Mark", "3"},
                        {"nt", "mark", "Mark", "4"},
                        {"nt", "mark", "Mark", "5"},
                        {"nt", "mark", "Mark", "6"},
                        {"nt", "mark", "Mark", "7"},
                        {"nt", "mark", "Mark", "8"},
                        {"nt", "mark", "Mark", "9"},
                        {"nt", "mark", "Mark", "10"},
                        {"nt", "mark", "Mark", "11"},
                        {"nt", "mark", "Mark", "12"},
                        {"nt", "mark", "Mark", "13"},
                        {"nt", "mark", "Mark", "14"},
                        {"nt", "mark", "Mark", "15"},
                        {"nt", "mark", "Mark", "16"},
                        {"nt", "luke", "Luke", "1"},
                        {"nt", "luke", "Luke", "2"},
                        {"nt", "luke", "Luke", "3"},
                        {"nt", "luke", "Luke", "4"},
                        {"nt", "luke", "Luke", "5"},
                        {"nt", "luke", "Luke", "6"},
                        {"nt", "luke", "Luke", "7"},
                        {"nt", "luke", "Luke", "8"},
                        {"nt", "luke", "Luke", "9"},
                        {"nt", "luke", "Luke", "10"},
                        {"nt", "luke", "Luke", "11"},
                        {"nt", "luke", "Luke", "12"},
                        {"nt", "luke", "Luke", "13"},
                        {"nt", "luke", "Luke", "14"},
                        {"nt", "luke", "Luke", "15"},
                        {"nt", "luke", "Luke", "16"},
                        {"nt", "luke", "Luke", "17"},
                        {"nt", "luke", "Luke", "18"},
                        {"nt", "luke", "Luke", "19"},
                        {"nt", "luke", "Luke", "20"},
                        {"nt", "luke", "Luke", "21"},
                        {"nt", "luke", "Luke", "22"},
                        {"nt", "luke", "Luke", "23"},
                        {"nt", "luke", "Luke", "24"},
                        {"nt", "john", "John", "1"},
                        {"nt", "john", "John", "2"},
                        {"nt", "john", "John", "3"},
                        {"nt", "john", "John", "4"},
                        {"nt", "john", "John", "5"},
                        {"nt", "john", "John", "6"},
                        {"nt", "john", "John", "7"},
                        {"nt", "john", "John", "8"},
                        {"nt", "john", "John", "9"},
                        {"nt", "john", "John", "10"},
                        {"nt", "john", "John", "11"},
                        {"nt", "john", "John", "12"},
                        {"nt", "john", "John", "13"},
                        {"nt", "john", "John", "14"},
                        {"nt", "john", "John", "15"},
                        {"nt", "john", "John", "16"},
                        {"nt", "john", "John", "17"},
                        {"nt", "john", "John", "18"},
                        {"nt", "john", "John", "19"},
                        {"nt", "john", "John", "20"},
                        {"nt", "john", "John", "21"},
                        {"nt", "acts", "Acts", "1"},
                        {"nt", "acts", "Acts", "2"},
                        {"nt", "acts", "Acts", "3"},
                        {"nt", "acts", "Acts", "4"},
                        {"nt", "acts", "Acts", "5"},
                        {"nt", "acts", "Acts", "6"},
                        {"nt", "acts", "Acts", "7"},
                        {"nt", "acts", "Acts", "8"},
                        {"nt", "acts", "Acts", "9"},
                        {"nt", "acts", "Acts", "10"},
                        {"nt", "acts", "Acts", "11"},
                        {"nt", "acts", "Acts", "12"},
                        {"nt", "acts", "Acts", "13"},
                        {"nt", "acts", "Acts", "14"},
                        {"nt", "acts", "Acts", "15"},
                        {"nt", "acts", "Acts", "16"},
                        {"nt", "acts", "Acts", "17"},
                        {"nt", "acts", "Acts", "18"},
                        {"nt", "acts", "Acts", "19"},
                        {"nt", "acts", "Acts", "20"},
                        {"nt", "acts", "Acts", "21"},
                        {"nt", "acts", "Acts", "22"},
                        {"nt", "acts", "Acts", "23"},
                        {"nt", "acts", "Acts", "24"},
                        {"nt", "acts", "Acts", "25"},
                        {"nt", "acts", "Acts", "26"},
                        {"nt", "acts", "Acts", "27"},
                        {"nt", "acts", "Acts", "28"},
                        {"nt", "rom", "Romans", "1"},
                        {"nt", "rom", "Romans", "2"},
                        {"nt", "rom", "Romans", "3"},
                        {"nt", "rom", "Romans", "4"},
                        {"nt", "rom", "Romans", "5"},
                        {"nt", "rom", "Romans", "6"},
                        {"nt", "rom", "Romans", "7"},
                        {"nt", "rom", "Romans", "8"},
                        {"nt", "rom", "Romans", "9"},
                        {"nt", "rom", "Romans", "10"},
                        {"nt", "rom", "Romans", "11"},
                        {"nt", "rom", "Romans", "12"},
                        {"nt", "rom", "Romans", "13"},
                        {"nt", "rom", "Romans", "14"},
                        {"nt", "rom", "Romans", "15"},
                        {"nt", "rom", "Romans", "16"},
                        {"nt", "1-cor", "1 Corinthians", "1"},
                        {"nt", "1-cor", "1 Corinthians", "2"},
                        {"nt", "1-cor", "1 Corinthians", "3"},
                        {"nt", "1-cor", "1 Corinthians", "4"},
                        {"nt", "1-cor", "1 Corinthians", "5"},
                        {"nt", "1-cor", "1 Corinthians", "6"},
                        {"nt", "1-cor", "1 Corinthians", "7"},
                        {"nt", "1-cor", "1 Corinthians", "8"},
                        {"nt", "1-cor", "1 Corinthians", "9"},
                        {"nt", "1-cor", "1 Corinthians", "10"},
                        {"nt", "1-cor", "1 Corinthians", "11"},
                        {"nt", "1-cor", "1 Corinthians", "12"},
                        {"nt", "1-cor", "1 Corinthians", "13"},
                        {"nt", "1-cor", "1 Corinthians", "14"},
                        {"nt", "1-cor", "1 Corinthians", "15"},
                        {"nt", "1-cor", "1 Corinthians", "16"},
                        {"nt", "2-cor", "2 Corinthians", "1"},
                        {"nt", "2-cor", "2 Corinthians", "2"},
                        {"nt", "2-cor", "2 Corinthians", "3"},
                        {"nt", "2-cor", "2 Corinthians", "4"},
                        {"nt", "2-cor", "2 Corinthians", "5"},
                        {"nt", "2-cor", "2 Corinthians", "6"},
                        {"nt", "2-cor", "2 Corinthians", "7"},
                        {"nt", "2-cor", "2 Corinthians", "8"},
                        {"nt", "2-cor", "2 Corinthians", "9"},
                        {"nt", "2-cor", "2 Corinthians", "10"},
                        {"nt", "2-cor", "2 Corinthians", "11"},
                        {"nt", "2-cor", "2 Corinthians", "12"},
                        {"nt", "2-cor", "2 Corinthians", "13"},
                        {"nt", "gal", "Galatians", "1"},
                        {"nt", "gal", "Galatians", "2"},
                        {"nt", "gal", "Galatians", "3"},
                        {"nt", "gal", "Galatians", "4"},
                        {"nt", "gal", "Galatians", "5"},
                        {"nt", "gal", "Galatians", "6"},
                        {"nt", "eph", "Ephesians", "1"},
                        {"nt", "eph", "Ephesians", "2"},
                        {"nt", "eph", "Ephesians", "3"},
                        {"nt", "eph", "Ephesians", "4"},
                        {"nt", "eph", "Ephesians", "5"},
                        {"nt", "eph", "Ephesians", "6"},
                        {"nt", "philip", "Philippians", "1"},
                        {"nt", "philip", "Philippians", "2"},
                        {"nt", "philip", "Philippians", "3"},
                        {"nt", "philip", "Philippians", "4"},
                        {"nt", "col", "Colossians", "1"},
                        {"nt", "col", "Colossians", "2"},
                        {"nt", "col", "Colossians", "3"},
                        {"nt", "col", "Colossians", "4"},
                        {"nt", "1-thes", "1 Thessalonians", "1"},
                        {"nt", "1-thes", "1 Thessalonians", "2"},
                        {"nt", "1-thes", "1 Thessalonians", "3"},
                        {"nt", "1-thes", "1 Thessalonians", "4"},
                        {"nt", "1-thes", "1 Thessalonians", "5"},
                        {"nt", "2-thes", "2 Thessalonians", "1"},
                        {"nt", "2-thes", "2 Thessalonians", "2"},
                        {"nt", "2-thes", "2 Thessalonians", "3"},
                        {"nt", "1-tim", "1 Timothy", "1"},
                        {"nt", "1-tim", "1 Timothy", "2"},
                        {"nt", "1-tim", "1 Timothy", "3"},
                        {"nt", "1-tim", "1 Timothy", "4"},
                        {"nt", "1-tim", "1 Timothy", "5"},
                        {"nt", "1-tim", "1 Timothy", "6"},
                        {"nt", "2-tim", "2 Timothy", "1"},
                        {"nt", "2-tim", "2 Timothy", "2"},
                        {"nt", "2-tim", "2 Timothy", "3"},
                        {"nt", "2-tim", "2 Timothy", "4"},
                        {"nt", "titus", "Titus", "1"},
                        {"nt", "titus", "Titus", "2"},
                        {"nt", "titus", "Titus", "3"},
                        {"nt", "philem", "Philemon", "1"},
                        {"nt", "heb", "Hebrews", "1"},
                        {"nt", "heb", "Hebrews", "2"},
                        {"nt", "heb", "Hebrews", "3"},
                        {"nt", "heb", "Hebrews", "4"},
                        {"nt", "heb", "Hebrews", "5"},
                        {"nt", "heb", "Hebrews", "6"},
                        {"nt", "heb", "Hebrews", "7"},
                        {"nt", "heb", "Hebrews", "8"},
                        {"nt", "heb", "Hebrews", "9"},
                        {"nt", "heb", "Hebrews", "10"},
                        {"nt", "heb", "Hebrews", "11"},
                        {"nt", "heb", "Hebrews", "12"},
                        {"nt", "heb", "Hebrews", "13"},
                        {"nt", "james", "James", "1"},
                        {"nt", "james", "James", "2"},
                        {"nt", "james", "James", "3"},
                        {"nt", "james", "James", "4"},
                        {"nt", "james", "James", "5"},
                        {"nt", "1-pet", "1 Peter", "1"},
                        {"nt", "1-pet", "1 Peter", "2"},
                        {"nt", "1-pet", "1 Peter", "3"},
                        {"nt", "1-pet", "1 Peter", "4"},
                        {"nt", "1-pet", "1 Peter", "5"},
                        {"nt", "2-pet", "2 Peter", "1"},
                        {"nt", "2-pet", "2 Peter", "2"},
                        {"nt", "2-pet", "2 Peter", "3"},
                        {"nt", "1-jn", "1 John", "1"},
                        {"nt", "1-jn", "1 John", "2"},
                        {"nt", "1-jn", "1 John", "3"},
                        {"nt", "1-jn", "1 John", "4"},
                        {"nt", "1-jn", "1 John", "5"},
                        {"nt", "2-jn", "2 John", "1"},
                        {"nt", "3-jn", "3 John", "1"},
                        {"nt", "jude", "Jude", "1"},
                        {"nt", "rev", "Revelation", "1"},
                        {"nt", "rev", "Revelation", "2"},
                        {"nt", "rev", "Revelation", "3"},
                        {"nt", "rev", "Revelation", "4"},
                        {"nt", "rev", "Revelation", "5"},
                        {"nt", "rev", "Revelation", "6"},
                        {"nt", "rev", "Revelation", "7"},
                        {"nt", "rev", "Revelation", "8"},
                        {"nt", "rev", "Revelation", "9"},
                        {"nt", "rev", "Revelation", "10"},
                        {"nt", "rev", "Revelation", "11"},
                        {"nt", "rev", "Revelation", "12"},
                        {"nt", "rev", "Revelation", "13"},
                        {"nt", "rev", "Revelation", "14"},
                        {"nt", "rev", "Revelation", "15"},
                        {"nt", "rev", "Revelation", "16"},
                        {"nt", "rev", "Revelation", "17"},
                        {"nt", "rev", "Revelation", "18"},
                        {"nt", "rev", "Revelation", "19"},
                        {"nt", "rev", "Revelation", "20"},
                        {"nt", "rev", "Revelation", "21"},
                        {"nt", "rev", "Revelation", "22"},
                        {"bofm", "1-ne", "1 Nephi", "1"},
                        {"bofm", "1-ne", "1 Nephi", "2"},
                        {"bofm", "1-ne", "1 Nephi", "3"},
                        {"bofm", "1-ne", "1 Nephi", "4"},
                        {"bofm", "1-ne", "1 Nephi", "5"},
                        {"bofm", "1-ne", "1 Nephi", "6"},
                        {"bofm", "1-ne", "1 Nephi", "7"},
                        {"bofm", "1-ne", "1 Nephi", "8"},
                        {"bofm", "1-ne", "1 Nephi", "9"},
                        {"bofm", "1-ne", "1 Nephi", "10"},
                        {"bofm", "1-ne", "1 Nephi", "11"},
                        {"bofm", "1-ne", "1 Nephi", "12"},
                        {"bofm", "1-ne", "1 Nephi", "13"},
                        {"bofm", "1-ne", "1 Nephi", "14"},
                        {"bofm", "1-ne", "1 Nephi", "15"},
                        {"bofm", "1-ne", "1 Nephi", "16"},
                        {"bofm", "1-ne", "1 Nephi", "17"},
                        {"bofm", "1-ne", "1 Nephi", "18"},
                        {"bofm", "1-ne", "1 Nephi", "19"},
                        {"bofm", "1-ne", "1 Nephi", "20"},
                        {"bofm", "1-ne", "1 Nephi", "21"},
                        {"bofm", "1-ne", "1 Nephi", "22"},
                        {"bofm", "2-ne", "2 Nephi", "1"},
                        {"bofm", "2-ne", "2 Nephi", "2"},
                        {"bofm", "2-ne", "2 Nephi", "3"},
                        {"bofm", "2-ne", "2 Nephi", "4"},
                        {"bofm", "2-ne", "2 Nephi", "5"},
                        {"bofm", "2-ne", "2 Nephi", "6"},
                        {"bofm", "2-ne", "2 Nephi", "7"},
                        {"bofm", "2-ne", "2 Nephi", "8"},
                        {"bofm", "2-ne", "2 Nephi", "9"},
                        {"bofm", "2-ne", "2 Nephi", "10"},
                        {"bofm", "2-ne", "2 Nephi", "11"},
                        {"bofm", "2-ne", "2 Nephi", "12"},
                        {"bofm", "2-ne", "2 Nephi", "13"},
                        {"bofm", "2-ne", "2 Nephi", "14"},
                        {"bofm", "2-ne", "2 Nephi", "15"},
                        {"bofm", "2-ne", "2 Nephi", "16"},
                        {"bofm", "2-ne", "2 Nephi", "17"},
                        {"bofm", "2-ne", "2 Nephi", "18"},
                        {"bofm", "2-ne", "2 Nephi", "19"},
                        {"bofm", "2-ne", "2 Nephi", "20"},
                        {"bofm", "2-ne", "2 Nephi", "21"},
                        {"bofm", "2-ne", "2 Nephi", "22"},
                        {"bofm", "2-ne", "2 Nephi", "23"},
                        {"bofm", "2-ne", "2 Nephi", "24"},
                        {"bofm", "2-ne", "2 Nephi", "25"},
                        {"bofm", "2-ne", "2 Nephi", "26"},
                        {"bofm", "2-ne", "2 Nephi", "27"},
                        {"bofm", "2-ne", "2 Nephi", "28"},
                        {"bofm", "2-ne", "2 Nephi", "29"},
                        {"bofm", "2-ne", "2 Nephi", "30"},
                        {"bofm", "2-ne", "2 Nephi", "31"},
                        {"bofm", "2-ne", "2 Nephi", "32"},
                        {"bofm", "2-ne", "2 Nephi", "33"},
                        {"bofm", "jacob", "Jacob", "1"},
                        {"bofm", "jacob", "Jacob", "2"},
                        {"bofm", "jacob", "Jacob", "3"},
                        {"bofm", "jacob", "Jacob", "4"},
                        {"bofm", "jacob", "Jacob", "5"},
                        {"bofm", "jacob", "Jacob", "6"},
                        {"bofm", "jacob", "Jacob", "7"},
                        {"bofm", "enos", "Enos", "1"},
                        {"bofm", "jarom", "Jarom", "1"},
                        {"bofm", "omni", "Omni", "1"},
                        {"bofm", "w-of-m", "Words of Mormon", "1"},
                        {"bofm", "mosiah", "Mosiah", "1"},
                        {"bofm", "mosiah", "Mosiah", "2"},
                        {"bofm", "mosiah", "Mosiah", "3"},
                        {"bofm", "mosiah", "Mosiah", "4"},
                        {"bofm", "mosiah", "Mosiah", "5"},
                        {"bofm", "mosiah", "Mosiah", "6"},
                        {"bofm", "mosiah", "Mosiah", "7"},
                        {"bofm", "mosiah", "Mosiah", "8"},
                        {"bofm", "mosiah", "Mosiah", "9"},
                        {"bofm", "mosiah", "Mosiah", "10"},
                        {"bofm", "mosiah", "Mosiah", "11"},
                        {"bofm", "mosiah", "Mosiah", "12"},
                        {"bofm", "mosiah", "Mosiah", "13"},
                        {"bofm", "mosiah", "Mosiah", "14"},
                        {"bofm", "mosiah", "Mosiah", "15"},
                        {"bofm", "mosiah", "Mosiah", "16"},
                        {"bofm", "mosiah", "Mosiah", "17"},
                        {"bofm", "mosiah", "Mosiah", "18"},
                        {"bofm", "mosiah", "Mosiah", "19"},
                        {"bofm", "mosiah", "Mosiah", "20"},
                        {"bofm", "mosiah", "Mosiah", "21"},
                        {"bofm", "mosiah", "Mosiah", "22"},
                        {"bofm", "mosiah", "Mosiah", "23"},
                        {"bofm", "mosiah", "Mosiah", "24"},
                        {"bofm", "mosiah", "Mosiah", "25"},
                        {"bofm", "mosiah", "Mosiah", "26"},
                        {"bofm", "mosiah", "Mosiah", "27"},
                        {"bofm", "mosiah", "Mosiah", "28"},
                        {"bofm", "mosiah", "Mosiah", "29"},
                        {"bofm", "alma", "Alma", "1"},
                        {"bofm", "alma", "Alma", "2"},
                        {"bofm", "alma", "Alma", "3"},
                        {"bofm", "alma", "Alma", "4"},
                        {"bofm", "alma", "Alma", "5"},
                        {"bofm", "alma", "Alma", "6"},
                        {"bofm", "alma", "Alma", "7"},
                        {"bofm", "alma", "Alma", "8"},
                        {"bofm", "alma", "Alma", "9"},
                        {"bofm", "alma", "Alma", "10"},
                        {"bofm", "alma", "Alma", "11"},
                        {"bofm", "alma", "Alma", "12"},
                        {"bofm", "alma", "Alma", "13"},
                        {"bofm", "alma", "Alma", "14"},
                        {"bofm", "alma", "Alma", "15"},
                        {"bofm", "alma", "Alma", "16"},
                        {"bofm", "alma", "Alma", "17"},
                        {"bofm", "alma", "Alma", "18"},
                        {"bofm", "alma", "Alma", "19"},
                        {"bofm", "alma", "Alma", "20"},
                        {"bofm", "alma", "Alma", "21"},
                        {"bofm", "alma", "Alma", "22"},
                        {"bofm", "alma", "Alma", "23"},
                        {"bofm", "alma", "Alma", "24"},
                        {"bofm", "alma", "Alma", "25"},
                        {"bofm", "alma", "Alma", "26"},
                        {"bofm", "alma", "Alma", "27"},
                        {"bofm", "alma", "Alma", "28"},
                        {"bofm", "alma", "Alma", "29"},
                        {"bofm", "alma", "Alma", "30"},
                        {"bofm", "alma", "Alma", "31"},
                        {"bofm", "alma", "Alma", "32"},
                        {"bofm", "alma", "Alma", "33"},
                        {"bofm", "alma", "Alma", "34"},
                        {"bofm", "alma", "Alma", "35"},
                        {"bofm", "alma", "Alma", "36"},
                        {"bofm", "alma", "Alma", "37"},
                        {"bofm", "alma", "Alma", "38"},
                        {"bofm", "alma", "Alma", "39"},
                        {"bofm", "alma", "Alma", "40"},
                        {"bofm", "alma", "Alma", "41"},
                        {"bofm", "alma", "Alma", "42"},
                        {"bofm", "alma", "Alma", "43"},
                        {"bofm", "alma", "Alma", "44"},
                        {"bofm", "alma", "Alma", "45"},
                        {"bofm", "alma", "Alma", "46"},
                        {"bofm", "alma", "Alma", "47"},
                        {"bofm", "alma", "Alma", "48"},
                        {"bofm", "alma", "Alma", "49"},
                        {"bofm", "alma", "Alma", "50"},
                        {"bofm", "alma", "Alma", "51"},
                        {"bofm", "alma", "Alma", "52"},
                        {"bofm", "alma", "Alma", "53"},
                        {"bofm", "alma", "Alma", "54"},
                        {"bofm", "alma", "Alma", "55"},
                        {"bofm", "alma", "Alma", "56"},
                        {"bofm", "alma", "Alma", "57"},
                        {"bofm", "alma", "Alma", "58"},
                        {"bofm", "alma", "Alma", "59"},
                        {"bofm", "alma", "Alma", "60"},
                        {"bofm", "alma", "Alma", "61"},
                        {"bofm", "alma", "Alma", "62"},
                        {"bofm", "alma", "Alma", "63"},
                        {"bofm", "hel", "Helaman", "1"},
                        {"bofm", "hel", "Helaman", "2"},
                        {"bofm", "hel", "Helaman", "3"},
                        {"bofm", "hel", "Helaman", "4"},
                        {"bofm", "hel", "Helaman", "5"},
                        {"bofm", "hel", "Helaman", "6"},
                        {"bofm", "hel", "Helaman", "7"},
                        {"bofm", "hel", "Helaman", "8"},
                        {"bofm", "hel", "Helaman", "9"},
                        {"bofm", "hel", "Helaman", "10"},
                        {"bofm", "hel", "Helaman", "11"},
                        {"bofm", "hel", "Helaman", "12"},
                        {"bofm", "hel", "Helaman", "13"},
                        {"bofm", "hel", "Helaman", "14"},
                        {"bofm", "hel", "Helaman", "15"},
                        {"bofm", "hel", "Helaman", "16"},
                        {"bofm", "3-ne", "3 Nephi", "1"},
                        {"bofm", "3-ne", "3 Nephi", "2"},
                        {"bofm", "3-ne", "3 Nephi", "3"},
                        {"bofm", "3-ne", "3 Nephi", "4"},
                        {"bofm", "3-ne", "3 Nephi", "5"},
                        {"bofm", "3-ne", "3 Nephi", "6"},
                        {"bofm", "3-ne", "3 Nephi", "7"},
                        {"bofm", "3-ne", "3 Nephi", "8"},
                        {"bofm", "3-ne", "3 Nephi", "9"},
                        {"bofm", "3-ne", "3 Nephi", "10"},
                        {"bofm", "3-ne", "3 Nephi", "11"},
                        {"bofm", "3-ne", "3 Nephi", "12"},
                        {"bofm", "3-ne", "3 Nephi", "13"},
                        {"bofm", "3-ne", "3 Nephi", "14"},
                        {"bofm", "3-ne", "3 Nephi", "15"},
                        {"bofm", "3-ne", "3 Nephi", "16"},
                        {"bofm", "3-ne", "3 Nephi", "17"},
                        {"bofm", "3-ne", "3 Nephi", "18"},
                        {"bofm", "3-ne", "3 Nephi", "19"},
                        {"bofm", "3-ne", "3 Nephi", "20"},
                        {"bofm", "3-ne", "3 Nephi", "21"},
                        {"bofm", "3-ne", "3 Nephi", "22"},
                        {"bofm", "3-ne", "3 Nephi", "23"},
                        {"bofm", "3-ne", "3 Nephi", "24"},
                        {"bofm", "3-ne", "3 Nephi", "25"},
                        {"bofm", "3-ne", "3 Nephi", "26"},
                        {"bofm", "3-ne", "3 Nephi", "27"},
                        {"bofm", "3-ne", "3 Nephi", "28"},
                        {"bofm", "3-ne", "3 Nephi", "29"},
                        {"bofm", "3-ne", "3 Nephi", "30"},
                        {"bofm", "4-ne", "4 Nephi", "1"},
                        {"bofm", "morm", "Mormon", "1"},
                        {"bofm", "morm", "Mormon", "2"},
                        {"bofm", "morm", "Mormon", "3"},
                        {"bofm", "morm", "Mormon", "4"},
                        {"bofm", "morm", "Mormon", "5"},
                        {"bofm", "morm", "Mormon", "6"},
                        {"bofm", "morm", "Mormon", "7"},
                        {"bofm", "morm", "Mormon", "8"},
                        {"bofm", "morm", "Mormon", "9"},
                        {"bofm", "ether", "Ether", "1"},
                        {"bofm", "ether", "Ether", "2"},
                        {"bofm", "ether", "Ether", "3"},
                        {"bofm", "ether", "Ether", "4"},
                        {"bofm", "ether", "Ether", "5"},
                        {"bofm", "ether", "Ether", "6"},
                        {"bofm", "ether", "Ether", "7"},
                        {"bofm", "ether", "Ether", "8"},
                        {"bofm", "ether", "Ether", "9"},
                        {"bofm", "ether", "Ether", "10"},
                        {"bofm", "ether", "Ether", "11"},
                        {"bofm", "ether", "Ether", "12"},
                        {"bofm", "ether", "Ether", "13"},
                        {"bofm", "ether", "Ether", "14"},
                        {"bofm", "ether", "Ether", "15"},
                        {"bofm", "moro", "Moroni", "1"},
                        {"bofm", "moro", "Moroni", "2"},
                        {"bofm", "moro", "Moroni", "3"},
                        {"bofm", "moro", "Moroni", "4"},
                        {"bofm", "moro", "Moroni", "5"},
                        {"bofm", "moro", "Moroni", "6"},
                        {"bofm", "moro", "Moroni", "7"},
                        {"bofm", "moro", "Moroni", "8"},
                        {"bofm", "moro", "Moroni", "9"},
                        {"bofm", "moro", "Moroni", "10"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "1"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "2"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "3"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "4"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "5"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "6"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "7"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "8"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "9"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "10"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "11"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "12"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "13"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "14"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "15"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "16"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "17"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "18"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "19"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "20"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "21"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "22"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "23"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "24"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "25"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "26"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "27"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "28"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "29"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "30"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "31"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "32"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "33"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "34"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "35"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "36"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "37"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "38"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "39"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "40"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "41"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "42"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "43"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "44"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "45"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "46"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "47"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "48"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "49"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "50"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "51"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "52"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "53"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "54"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "55"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "56"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "57"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "58"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "59"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "60"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "61"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "62"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "63"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "64"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "65"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "66"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "67"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "68"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "69"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "70"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "71"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "72"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "73"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "74"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "75"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "76"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "77"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "78"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "79"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "80"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "81"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "82"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "83"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "84"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "85"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "86"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "87"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "88"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "89"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "90"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "91"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "92"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "93"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "94"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "95"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "96"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "97"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "98"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "99"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "100"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "101"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "102"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "103"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "104"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "105"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "106"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "107"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "108"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "109"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "110"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "111"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "112"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "113"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "114"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "115"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "116"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "117"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "118"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "119"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "120"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "121"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "122"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "123"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "124"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "125"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "126"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "127"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "128"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "129"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "130"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "131"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "132"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "133"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "134"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "135"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "136"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "137"},
                        {"dc-testament", "dc", "Doctrine and Covenants", "138"},
                        {"pgp", "moses", "Moses", "1"},
                        {"pgp", "moses", "Moses", "2"},
                        {"pgp", "moses", "Moses", "3"},
                        {"pgp", "moses", "Moses", "4"},
                        {"pgp", "moses", "Moses", "5"},
                        {"pgp", "moses", "Moses", "6"},
                        {"pgp", "moses", "Moses", "7"},
                        {"pgp", "moses", "Moses", "8"},
                        {"pgp", "abr", "Abraham", "1"},
                        {"pgp", "abr", "Abraham", "2"},
                        {"pgp", "abr", "Abraham", "3"},
                        {"pgp", "abr", "Abraham", "4"},
                        {"pgp", "abr", "Abraham", "5"},
                        {"pgp", "js-m", "Joseph Smith--Matthew", "1"},
                        {"pgp", "js-h", "Joseph Smith--History", "1"},
                        {"pgp", "a-of-f", "Articles of Faith", "1"}
                };

        Random random = new Random();
        int gospelNum = random.nextInt(library.length);
        System.out.println(library[gospelNum][0] +
                " " +
                library[gospelNum][1] +
                " " +
                library[gospelNum][2] +
                " " +
                library[gospelNum][3]);
        return library[gospelNum];
    }
}
